local LAYOUT = {
		path = "/assets/keyboard/",
		{name = '1', pos = {x = 1, y = 0}, alias = '1'},
		{name = '2', pos = {x = 2, y = 0}, alias = '2'},
		{name = '3', pos = {x = 3, y = 0}, alias = '3'},
		{name = '4', pos = {x = 4, y = 0}, alias = '4'},
		{name = '5', pos = {x = 5, y = 0}, alias = '5'},
		{name = '6', pos = {x = 6, y = 0}, alias = '6'},
		{name = '7', pos = {x = 7, y = 0}, alias = '7'},
		{name = '8', pos = {x = 8, y = 0}, alias = '8'},
		{name = '9', pos = {x = 9, y = 0}, alias = '9'},
		{name = '0', pos = {x = 10, y = 0}, alias = '0'},
		{name = 'q', pos = {x = 1.5, y = 1}},
		{name = 'w', pos = {x = 2.5, y = 1}},
		{name = 'e', pos = {x = 3.5, y = 1}},
		{name = 'r', pos = {x = 4.5, y = 1}},
		{name = 't', pos = {x = 5.5, y = 1}},
		{name = 'y', pos = {x = 6.5, y = 1}},
		{name = 'u', pos = {x = 7.5, y = 1}},
		{name = 'i', pos = {x = 8.5, y = 1}},
		{name = 'o', pos = {x = 9.5, y = 1}},
		{name = 'p', pos = {x = 10.5, y = 1}},
		{name = 'a', pos = {x = 2, y = 2}},
		{name = 's', pos = {x = 3, y = 2}},
		{name = 'd', pos = {x = 4, y = 2}},
		{name = 'f', pos = {x = 5, y = 2}},
		{name = 'g', pos = {x = 6, y = 2}},
		{name = 'h', pos = {x = 7, y = 2}},
		{name = 'j', pos = {x = 8, y = 2}},
		{name = 'k', pos = {x = 9, y = 2}},
		{name = 'l', pos = {x = 10, y = 2}},
		{name = 'z', pos = {x = 2.5, y = 3}},
		{name = 'x', pos = {x = 3.5, y = 3}},
		{name = 'c', pos = {x = 4.5, y = 3}},
		{name = 'v', pos = {x = 5.5, y = 3}},
		{name = 'b', pos = {x = 6.5, y = 3}},
		{name = 'n', pos = {x = 7.5, y = 3}},
		{name = 'm', pos = {x = 8.5, y = 3}},
		{name = 'space', pos = {x = 3, y = 4}},
		{name = 'tab', pos = {x = 0, y = 1}},
		{name = 'lshift', pos = {x = 0, y = 3}},
		{name = 'lcontrol', pos = {x = 0, y = 4}},
		{name = 'lgui', pos = {x = 1, y = 4}},
		{name = 'lalt', pos = {x = 2, y = 4}},
		{name = 'capslock', pos = {x = 0, y = 2}},
		{name = 'space', pos = {x = 3, y = 4}},
		{name = 'lclick', pos = {x = 12, y = 0}},
		{name = 'mclick', pos = {x = 13, y = 0}},
		{name = 'wheelup', pos = {x = 13, y = 1}},
		{name = 'wheeldown', pos = {x = 13, y = 1.5}},
		{name = 'rclick', pos = {x = 14, y = 0}},
	}
return LAYOUT